version: "3.9"
services:
  absa:
    build:
      context: . # set as root of the repo (outer AEOCFO folder)
    volumes:
      - ./logs:/app/logs
    command: ["python", "AEOCFO/Pipeline/ABSA.py", "--testing"]

  oasis:
    build:
      context: .
    volumes:
      - ./logs:/app/logs
    command: ["python", "AEOCFO/Pipeline/OASIS.py", "--testing"]

  fr:
    build:
      context: .
    volumes:
      - ./logs:/app/logs
    command: ["python", "AEOCFO/Pipeline/FR.py", "--testing"]

  contingency:
    build:
      context: .
    volumes:
      - ./logs:/app/logs
    command: ["python", "AEOCFO/Pipeline/Contingency.py", "--testing"]

  manual-run:
    build:
      context: .
    volumes:
      - ./logs:/app/logs
    tty: true
    stdin_open: true
    command: ["python", "AEOCFO/Pipeline/Any.py", "--dataset", "FR", "--testing"]