ABSA_INPUT_FOLDER_ID = "1nlYOz8brWYgF3aKsgzpjZFIy1MmmEVxQ"
ABSA_OUTPUT_FOLDER_ID = "1ELodPGvuV7UZRhTl1x4Phh0PzMDescyG"
OASIS_INPUT_FOLDER_ID = "1WwgSJoEyz1RKsdSJop3oSDlZ5LqZ_ZKz"
OASIS_OUTPUT_FOLDER_ID = "1r-1xZMnqYkp1BS59Mnq4Gs3z0yKeUAIL"
CONTINGENCY_INPUT_FOLDER_ID = "1pNoRbJgNeVacqr4RzTbYCi1DVZ1qiwzP"
CONTINGENCY_OUTPUT_FOLDER_ID = "1w1g7xvVNKSX2RgHVhuN9UsDB_HLUkLOj"

OVERWRITE_FOLDER_ID = '1j9cbFLhxlP4CeH1nfdVlHRNbkpXEwyzi'

def get_overwrite_folder_id():
    return OVERWRITE_FOLDER_ID

def get_absa_folder_id():
    return ABSA_INPUT_FOLDER_ID, ABSA_OUTPUT_FOLDER_ID

def get_oasis_folder_id():
    return OASIS_INPUT_FOLDER_ID, OASIS_OUTPUT_FOLDER_ID

def get_contingency_folder_id():
    return CONTINGENCY_INPUT_FOLDER_ID, CONTINGENCY_OUTPUT_FOLDER_ID