name: Run Full Testing Workflow

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main
  workflow_call:  # Allows other workflows to call this setup

jobs:
  Setup: 
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.8

      - name: Cache Dependencies
        id: CacheStep
        uses: actions/cache@v3
        env: 
          cache-name: absa-auto-env
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Install Dependencies and Spacy Model
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_md
          pip install -e . 
      
      # Debugs
      - name: Debug Check -> Disply Installed SpaCy Models
        run: python -m spacy validate

      - name: Debug Check -> Disply Installed Packages
        run: pip list

      - name: Debug Check -> Disply Python Path
        run: python -c "import sys; print(sys.path)"

      - name: Setup -> Initialize Credentials # initialize credentials first or else authenticators.py will fail during build
        run: |
          printf '%s' '${{ secrets.GCP_CREDENTIALS }}' > credentials.json
          printf '%s' '${{ secrets.GCP_PUSHER_CREDS }}' > ocfo-primary-pusher.json
    
      - name: Debug Check -> Confirm AEOCFO is recognizeable # this one tends to bug so I want to have sys.path info before this runs if it fails
        run: python -c "import AEOCFO; print('AEOCFO is recognized!')"

      - name: Debug Check -> Test Pathing
        run: python debugs/check_pathing.py

      - name: Debug Check -> Test Google Service Account Permissions
        run: python debugs/check_permissions.py

  ABSA:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.8

      - name: Cache Dependencies
        id: CacheStep
        uses: actions/cache@v3
        env: 
          cache-name: absa-auto-env
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Install Dependencies and Spacy Model
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e . 

      - name: Setup -> Initialize Credentials
        run: |
          printf '%s' '${{ secrets.GCP_CREDENTIALS }}' > credentials.json
          printf '%s' '${{ secrets.GCP_PUSHER_CREDS }}' > ocfo-primary-pusher.json
      
      - name: Execute -> Process ABSA Raw Files
        run: python AEOCFO/Pipeline/Any.py --dataset 'ABSA' --testing --no-bigquery --halt-push

  Contingency:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.8

      - name: Cache Dependencies
        id: CacheStep
        uses: actions/cache@v3
        env: 
          cache-name: absa-auto-env
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Install Dependencies and Spacy Model
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e . 

      - name: Setup -> Initialize Credentials
        run: |
          printf '%s' '${{ secrets.GCP_CREDENTIALS }}' > credentials.json
          printf '%s' '${{ secrets.GCP_PUSHER_CREDS }}' > ocfo-primary-pusher.json
      
      - name: Execute -> Process Finance Committee Contingency Raw Files
        run: python AEOCFO/Pipeline/Any.py --dataset 'Contingency' --testing --no-bigquery --halt-push

  OASIS:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.8

      - name: Cache Dependencies
        id: CacheStep
        uses: actions/cache@v3
        env: 
          cache-name: absa-auto-env
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Install Dependencies and Spacy Model
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e . 

      - name: Setup -> Initialize Credentials
        run: |
          printf '%s' '${{ secrets.GCP_CREDENTIALS }}' > credentials.json
          printf '%s' '${{ secrets.GCP_PUSHER_CREDS }}' > ocfo-primary-pusher.json
      
      - name: Execute -> Process OASIS Raw Files
        run: python AEOCFO/Pipeline/Any.py --dataset 'OASIS' --testing --no-bigquery --halt-push
  FR:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.8

      - name: Cache Dependencies
        id: CacheStep
        uses: actions/cache@v3
        env: 
          cache-name: absa-auto-env
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Install Dependencies and Spacy Model
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e . 

      - name: Setup -> Initialize Credentials
        run: |
          printf '%s' '${{ secrets.GCP_CREDENTIALS }}' > credentials.json
          printf '%s' '${{ secrets.GCP_PUSHER_CREDS }}' > ocfo-primary-pusher.json
      
      - name: Execute -> Process FR Resos Raw Files
        run: python AEOCFO/Pipeline/Any.py --dataset 'FR' --testing --no-bigquery --halt-push