name: Run ABSA Processing Pipeline

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main
  workflow_call:  # Allows other workflows to call this setup

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.8

      - name: Cache Dependencies
        id: CacheStep
        uses: actions/cache@v3
        env: 
          cache-name: absa-auto-env
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Install Dependencies and Spacy Model
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e . 

      - name: Debug Check -> Disply Installed Packages
        run: pip list

      - name: Install Spacy Model
        run: python -m spacy download en_core_web_md

      - name: Debug Check -> Disply Installed SpaCy Models
        run: python -m spacy validate

      - name: Debug Check -> Disply Python Path
        run: python -c "import sys; print(sys.path)"

      - name: Debug Check -> List ASUC Explore
        run: pip list | grep ASUCExplore
    
      - name: Debug Check -> Confirm ASUCExplore is recognizeable
        run: python -c "import ASUCExplore; print('ASUCExplore is recognized!')"
      
      - name: Debug Check -> Test Pathing
        run: python scripts/debugs/check_pathing.py

      - name: Setup Credentials
        run: printf '%s' '${{ secrets.GCP_CREDENTIALS }}' > credentials.json

      - name: Debug Check -> Test Google Service Account Permissions
        run: python scripts/debugs/check_permissions.py
      
      - name: Process ABSA Raw Files
        run: python scripts/absa_master.py